const { DataTypes } = require("@sequelize/core");

const OsuUserModel = (db) => db.define('OsuUser', {
    user_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true, },
    username: { type: DataTypes.STRING, allowNull: false, },
    post_count: { type: DataTypes.INTEGER, allowNull: false, },
    comments_count: { type: DataTypes.INTEGER, allowNull: false, },
    level: { type: DataTypes.FLOAT, allowNull: false, },
    global_rank: { type: DataTypes.INTEGER, allowNull: false, },
    pp: { type: DataTypes.FLOAT, allowNull: false, },
    ranked_score: { type: DataTypes.BIGINT, allowNull: false, },
    playcount: { type: DataTypes.INTEGER, allowNull: false, },
    playtime: { type: DataTypes.INTEGER, allowNull: false, },
    total_score: { type: DataTypes.BIGINT, allowNull: false, },
    total_hits: { type: DataTypes.INTEGER, allowNull: false, },
    replays_watched: { type: DataTypes.INTEGER, allowNull: false, },
    ss_count: { type: DataTypes.INTEGER, allowNull: false, },
    ssh_count: { type: DataTypes.INTEGER, allowNull: false, },
    s_count: { type: DataTypes.INTEGER, allowNull: false, },
    sh_count: { type: DataTypes.INTEGER, allowNull: false, },
    a_count: { type: DataTypes.INTEGER, allowNull: false, },
    country_rank: { type: DataTypes.INTEGER, allowNull: false, },
    hit_accuracy: { type: DataTypes.FLOAT, allowNull: false, },
    b_count: { type: DataTypes.INTEGER, allowNull: false, },
    c_count: { type: DataTypes.INTEGER, allowNull: false, },
    d_count: { type: DataTypes.INTEGER, allowNull: false, },
    total_pp: { type: DataTypes.FLOAT, allowNull: false, },
    cover_url: { type: DataTypes.STRING, allowNull: false, },
    country_ss_rank: { type: DataTypes.INTEGER, allowNull: false, },
    country_ss_rank_highest: { type: DataTypes.INTEGER, allowNull: false, },
    country_ss_rank_highest_date: { type: DataTypes.DATE, allowNull: false, },
    global_ss_rank: { type: DataTypes.INTEGER, allowNull: false, },
    global_ss_rank_highest: { type: DataTypes.INTEGER, allowNull: false, },
    global_ss_rank_highest_date: { type: DataTypes.DATE, allowNull: false, },
    country_code: { type: DataTypes.STRING, allowNull: false, },
    country_name: { type: DataTypes.STRING, allowNull: false, },
    alt_ssh_count: { type: DataTypes.INTEGER, allowNull: false, },
    alt_ss_count: { type: DataTypes.INTEGER, allowNull: false, },
    alt_s_count: { type: DataTypes.INTEGER, allowNull: false, },
    alt_sh_count: { type: DataTypes.INTEGER, allowNull: false, },
    alt_a_count: { type: DataTypes.INTEGER, allowNull: false, },
    badges: { type: DataTypes.JSON, allowNull: false, },
    medals: { type: DataTypes.JSON, allowNull: false, },
}, {
    tableName: 'osu_users',
    timestamps: false
});
module.exports.OsuUserModel = OsuUserModel;